node {
  stage("Clone the project") {
    git branch: 'dev', url: 'https://github.com/edward313/Ecommerce_BE.git'
  }

  stage("Compilation") {
    sh "cd source"
    sh "./mvnw clean install -DskipTests"
  }

  stage("Tests and Deployment") {
    stage("Runing unit tests") {

      sh "./mvnw test -Punit"
    }
    stage("Deployment") {
      sh 'nohup ./mvnw spring-boot:run -Dserver.port=8001 &'
    }
  }
}